### ISSUE TITLE
Issues with running on Spyder 5.0.5

### ISSUE THREAD

**Issue by sgbaird** [lrcfmd/ElM2D#1]
Works fine in Juptyer notebook. Spyder is having issues. Can you reproduce this behavior? Or does it work fine in Spyder for you? It's via its own anaconda environment.
```python
    exitcode = _main(fd)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sterg\Documents\GitHub\sparks-baird\ElM2D-test\test.py", line 21, in <module>
    embedding = mapper.fit_transform(df["formula"])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 188, in fit_transform
    self.fit(X)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 176, in fit
    dist_vec = self._process_list(X, n_proc=self.n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 384, in _process_list
    process_pool = Pool(n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
100%|##########| 100/100 [00:20<00:00,  4.79it/s]
 95%|#########5| 95/100 [00:19<00:00,  5.26it/s]s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sterg\Documents\GitHub\sparks-baird\ElM2D-test\test.py", line 21, in <module>
    embedding = mapper.fit_transform(df["formula"])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 188, in fit_transform
    self.fit(X)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 176, in fit
    dist_vec = self._process_list(X, n_proc=self.n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 384, in _process_list
    process_pool = Pool(n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
100%|##########| 100/100 [00:20<00:00,  4.84it/s]
100%|##########| 100/100 [00:20<00:00,  4.88it/s]]
100%|##########| 99/99 [00:00<00:00, 49639.70it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sterg\Documents\GitHub\sparks-baird\ElM2D-test\test.py", line 21, in <module>
    embedding = mapper.fit_transform(df["formula"])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 188, in fit_transform
    self.fit(X)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 176, in fit
    dist_vec = self._process_list(X, n_proc=self.n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 384, in _process_list
    process_pool = Pool(n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sterg\Documents\GitHub\sparks-baird\ElM2D-test\test.py", line 21, in <module>
    embedding = mapper.fit_transform(df["formula"])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 188, in fit_transform
    self.fit(X)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 176, in fit
    dist_vec = self._process_list(X, n_proc=self.n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 384, in _process_list
    process_pool = Pool(n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
100%|##########| 100/100 [00:20<00:00,  4.87it/s]
100%|##########| 99/99 [00:00<00:00, 49830.32it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sterg\Documents\GitHub\sparks-baird\ElM2D-test\test.py", line 21, in <module>
    embedding = mapper.fit_transform(df["formula"])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 188, in fit_transform
    self.fit(X)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 176, in fit
    dist_vec = self._process_list(X, n_proc=self.n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 384, in _process_list
    process_pool = Pool(n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
100%|##########| 100/100 [00:20<00:00,  4.87it/s]
100%|##########| 100/100 [00:20<00:00,  4.79it/s]]
100%|##########| 100/100 [00:20<00:00,  4.78it/s]]
100%|##########| 99/99 [00:00<00:00, 49627.84it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sterg\Documents\GitHub\sparks-baird\ElM2D-test\test.py", line 21, in <module>
    embedding = mapper.fit_transform(df["formula"])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 188, in fit_transform
    self.fit(X)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 176, in fit
    dist_vec = self._process_list(X, n_proc=self.n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 384, in _process_list
    process_pool = Pool(n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sterg\Documents\GitHub\sparks-baird\ElM2D-test\test.py", line 21, in <module>
    embedding = mapper.fit_transform(df["formula"])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 188, in fit_transform
    self.fit(X)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 176, in fit
    dist_vec = self._process_list(X, n_proc=self.n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 384, in _process_list
    process_pool = Pool(n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sterg\Documents\GitHub\sparks-baird\ElM2D-test\test.py", line 21, in <module>
    embedding = mapper.fit_transform(df["formula"])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 188, in fit_transform
    self.fit(X)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 176, in fit
    dist_vec = self._process_list(X, n_proc=self.n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 384, in _process_list
    process_pool = Pool(n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
100%|##########| 100/100 [00:20<00:00,  4.86it/s]
100%|##########| 99/99 [00:00<00:00, 99220.09it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sterg\Documents\GitHub\sparks-baird\ElM2D-test\test.py", line 21, in <module>
    embedding = mapper.fit_transform(df["formula"])
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 188, in fit_transform
    self.fit(X)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 176, in fit
    dist_vec = self._process_list(X, n_proc=self.n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\site-packages\ElM2D\ElM2D.py", line 384, in _process_list
    process_pool = Pool(n_proc)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\sterg\anaconda3\envs\ElM2D\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
 52%|#####2    | 52/100 [00:11<00:10,  4.75it/s]
```

**Comment by sgbaird** [comment]
[Python multiprocessing RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase](https://stackoverflow.com/questions/61931669/python-multiprocessing-runtimeerror-an-attempt-has-been-made-to-start-a-new-pro)
> Multiprocessing usually doesn't work in a console/ide in Windows. When using a spawning system instead of fork, python must import modules and create state in the child process to get things to work. If you do not protect your outer script with a if __name__=="__main__": clause, you get this problem.

**Comment by sgbaird** [comment]
However, what's odd is the `ElM2D` does seem to have this:
https://github.com/lrcfmd/ElM2D/blob/7c82fdcfed984cfbfe5d2f77e87156bdb00dd110/ElM2D/ElM2D.py#L510-L511

Another related SE post:
https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing

Is it possible that the pip-installed version didn't include the if `__name__ == "__main__":` clause?

**Comment by sgbaird** [comment]
> (Spyder maintainer here) Multiprocessing doesn't work well on Windows in Spyder's IPython console. However, you can run your code in an external terminal to have the results you want.
> 
> To do that, please go to
> 
> Run > Configuration per file > Execute in an external system terminal
https://stackoverflow.com/a/48099756/13697228

**Comment by sgbaird** [comment]
Didn't get it to work even with that unfortunately. Instead, probably just need to be OK with not running in Spyder. https://stackoverflow.com/a/52768747/13697228
