### ISSUE TITLE
Numba needs NumPy 1.20 or less (import umap)

### ISSUE THREAD

**Issue by sgbaird** [lrcfmd/ElM2D#8]
```python
Traceback (most recent call last):
  File "c:\Users\sterg\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_vars.py", line 419, in evaluate_expression
    compiled = compile(_expression_to_evaluate(expression), '<string>', 'eval')
  File "<string>", line 1
    import umap
    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sterg\Anaconda3\envs\elm2d_\lib\site-packages\umap\__init__.py", line 2, in <module>
    from .umap_ import UMAP
  File "C:\Users\sterg\Anaconda3\envs\elm2d_\lib\site-packages\umap\umap_.py", line 28, in <module>
    import numba
  File "C:\Users\sterg\Anaconda3\envs\elm2d_\lib\site-packages\numba\__init__.py", line 198, in <module>
    _ensure_critical_deps()
  File "C:\Users\sterg\Anaconda3\envs\elm2d_\lib\site-packages\numba\__init__.py", line 138, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.20 or less")
ImportError: Numba needs NumPy 1.20 or less
```

**Comment by sgbaird** [comment]
Actually, maybe this is because of another dependency I installed. Either way, I did:
```python
conda install numpy=1.20
```
and it seemed to fix it.
